version: '3'
services: 
  elasticsearch:
    build: ./es
    ports:
    - "9200:9200"
    - "9300:9300"
    volumes:
    - /var/www/db:/www/data
  nebula:
    build: ./neb
    network_mode: "host"
    environment:
    - PORT=80
    volumes:
    - ./data:/data
  omniview:
    build: ./omni
    network_mode: "host"
    volumes:
    - ./data:/data
